# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ciao": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://bru08.github.io/nbdev_try/"

git_url = "https://github.com/bru08/nbdev_try/tree/master/"

def custom_doc_links(name): return None
